code-differently/code-society-25-2

.github/workflows/check_push.yml

chore: allow manual runs of push workflow

---

syllabus/README.md

docs: updates slides link

---

lib/javascript/grader/src/main.ts

fix: removes tentative grade from comment

---

.github/workflows/check_push.yml

fix: removes broken gh action check

---

lesson_01/README.md

docs: adding stretch details to the assignment

---

lesson_01/README.md

chore: fixed typo in stretch details

---

.github/workflows/check_lesson_02_java_pr.yaml

chore: adds an additional check for the stretch assignment

---

lesson_04/README.md
lesson_04/anthonydmays/README.md
lesson_05/README.md

feat: adds lesson_04 homework and lesson_05 pre-work

---

lesson_03/quiz/quiz.yaml
lesson_03/quiz/src/quizzes/brooklyn_harden_quiz.ts
lesson_03/quiz/src/quizzes/quizzes.module.ts

Problem: 
I ran into a problem with my terminal not allowing me to run 'npm run check.' It gave me the message that 'slice is not valid mach-o file' -- 'dlopen(...)' failed for 'bcrypt_lib.node.' Something along those lines, so I believe there was a corruption on my end so I just recloned the repo and installed all the dependencies and everything was fine once I redid all that.

feat: Brooklyn Harden created the ts file that included quiz questions and answers

---

lesson_05/README.md
lesson_06/README.md

feat: adds lesson_05 homework and lesson_06 pre-work

---

lesson_05/README.md

docs: fix bug with assignment details

---

lib/javascript/grader/src/main.ts

chore: removes existing PR message

---

lesson_04/deanwalston/Dean_W_PrimeNumber.py
lesson_04/deanwalston/Dean_W_PrimeNumberTest.py
lesson_04/deanwalston/README.md
lesson_04/deanwalston/package-lock.json
lesson_04/deanwalston/package/dean_w_prime_number_check.js
lesson_04/deanwalston/package/dean_w_prime_number_check.test.js
lesson_04/deanwalston/package/package-lock.json
lesson_04/deanwalston/package/package.json

Lesson 04 Prime Number Checker
This project contains two implementations of a prime number checking algorithm in both Python and Javascript. I have a README file with explanation of the project, implementation, and how to test.

feat: Dean adds Lesson_04 prime number checker 

---

lesson_04/evanderblue/README.md
lesson_04/evanderblue/prime_num.js
lesson_04/evanderblue/prime_number.py

This pull request contains three files for the lesson_04 assignment:
- README.md – Includes code examples in both JavaScript and Python, along with explanations of the functions used to check for prime numbers.
- prime_number.py_ – Python implementation of the prime number check function, including unit tests.
- prime_num.js – JavaScript implementation of the prime number check function, including unit tests.

feat: adds files from evanderblue for lesson_04 assignment

---

lesson_04/kerryferguson/README.md
lesson_04/kerryferguson/package.json
lesson_04/kerryferguson/prime_checker.js
lesson_04/kerryferguson/prime_checker.py
lesson_04/kerryferguson/test_prime_checker.py
lesson_04/kerryferguson/test_runner.js

Here is my lesson 04 folder, which contains the README with comparisons of a JavaScript and a Python prime checker, the JavaScript and Python files themselves, and test files for both programs.
Lessons Learned:
- What to look at when comparing programming languages
- Learning to double check what copilot does in case it is incorrect (had to delete many files)

feat: Adds kerryferguson folder for lesson 04 with language comparisons

---

lesson_05/marthao/myfitnesspal-user-stories/README.md

This PR includes a README document with the user stories and acceptance criteria for the MyFitnessPal app. 
Reflections:
The app has a lot of overlapping features, so the challenge was being specific enough about the user stories and acceptance criteria to make sure I was describing distinct functionality. 
Also, I slightly updated the naming convention of my PR to align with Anthony's style, and plan to use this format moving forward.

feat: adds Martha's user stories for lesson 05

---

lesson_05/trishtanhusser/README.md

feat: adds lesson05 README

---

lesson_05/trinitiejackson/USER_STORIES.md

This is the user store for lesson_05_homework.
I had a lot of fun creating user stories for this fantasy system. The nation itself came from a class project where my friends and I had to make a country/nation. We ended up loving the concept, even though we didn't have any concrete plans for its future. Now, one of my friends, who cosplays, is considering incorporating this nation as a part of his personal brand or persona. This made me excited to further develop its background, so I could help him if he decides to move forward with the idea.
The main difficulties I had were related to the bug issues. There are only so many issues we can identify, and I didn't want to seem repetitive by pointing out the same problems and results multiple times.

feat: adds Trinitie's lesson_05 user stories

---

lesson_09/types/types_app/src/main/java/com/codedifferently/lesson9/dataprovider/MarthaOfuaniProvider.java
lesson_09/types/types_app/src/main/resources/data/marthaofuani.json

Reflections:
- The main assignment was pretty straightforward, unlike the stretch assignment.

feat: adds Martha's data provider and json files for lesson 09 

---

lesson_12/README.md

chore: adds lecture recording link for lesson_12

---

slides/src/Slides/Lessons/Lesson11.js

docs: corrects lesson11 slides

---

lesson_05/jaydenellis/README.md

Im making a new pull request, let me know if this works and I deleting the old request

lesson_05 user stories complete

---

lib/javascript/grader/src/main.ts

fix: adjusts the prompt to ensure student is not addressed directly

---

project_oop/README.md

docs: updates feedback requirements

---

lesson_16/objects/objects_app/src/main/java/com/codedifferently/lesson16/deanwalston/CasinoDean.java
lesson_16/objects/objects_app/src/test/java/com/codedifferently/lesson16/deanwalston/CasinoDeanTest.java

Lesson 16
Included betting and revenue features, exceptions and add unit tests.

feat: Dean implements CasinoDean and Unit Test for Lesson 16

---

lesson_20/README.md
lesson_21/README.md

feat: adds lesson_20 homework and lesson_21 pre-work

---

lesson_21/README.md
lesson_22/README.md

docs: adds lesson_21 and lesson_22 readmes

---

.github/workflows/check_lesson_23_java_pr.yaml
.github/workflows/check_lesson_23_ts_pr.yaml

chore: adds automated checks for lesson 23
